id: P003108
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W2MS813
  title: 'ནམ་མཁའི་ནོར་བུའི་གསུང་རྩོམ་ཕྱོགས་བསྒྲིགས། '
  author: ''
  volumes:
    47a9b594ca3642c6a774958af7481f9c:
      image_group_id: I1KG572
      title: ''
      volume_number: 1
      total_pages: 654
      base_file: v001.txt
