id: I3344D604
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T12:33:21+00:00'
last_modified: '2022-06-07T17:38:37.611821+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2MS813
  title: 'ནམ་མཁའི་ནོར་བུའི་གསུང་རྩོམ་ཕྱོགས་བསྒྲིགས། '
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    E184:
      image_group_id: I1KG572
      title: ''
      total_pages: 654
      order: 1
      base_file: E184.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
